const initialDetails = {
  ticketNo: "",
  dateApprehension: null,
  confiscatedDL: "",
  name: "",
  address: "",
  typeVehicle: "",
  franchiseNo: "",
  plateNo: "",
  timeViolation: null,
  placeViolation: "",
  officer: null,
  violation: [],
  paid: false,
  remarks: "",
  amount: "",
  or: "",
  ortf: "",
  orDate: null,
  others: "",
  payor: "",
  receiptNo: "",
  datePaid: null,
  collectingOfficer: "",
};

export default { initialDetails };
